services:
    poll:
        build: ./poll
        ports:
            - "5000:80"
        networks:
            - poll-tier
        restart: always
        environment:
            - 0.0.0.0
        depends_on:
            - redis
    redis:
        image: redis:alpine
        expose:
            - 6379
        ports:
            - "6379:6379"
        networks:
            - poll-tier
            - back-tier
        restart: always
    worker:
        build: ./worker
        networks:
            - back-tier
        restart: always
        environment:
            - 0.0.0.0
        depends_on:
            - db
    db:
        image: postgres:13.0
        volumes:
            - db-data:/var/lib/postgresql/data
            - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
        networks:
            - result-tier
            - back-tier
        restart: always
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=password"
    result:
        build: ./result
        ports:
            - "5001:80"
        networks:
            - result-tier
        restart: always
        environment:
            - 0.0.0.0
        depends_on:
            - db

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data: